name: codable
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types.
version: 1.0.0
homepage: https://github.com/stablekernel/dart-codable
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
