name: conduit_codable
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types.
version: 1.0.0-b2
homepage: https://github.com/conduit-dart/conduit-codable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.4
  
